language: objective-c

before_install:
  - brew update
  - /usr/bin/which ruby
  - ruby --version

install:
  - brew tap csdms/models
  - brew tap --repair
  - brew install hydrotrend child
  - brew test hydrotrend
  - brew install sedflux --HEAD
  - brew test sedflux
  - brew install cem --HEAD
  - brew install adi2d --HEAD
  - brew install aquatellus --HEAD
  - brew install flowvel2d --HEAD
