language: objective-c

before_install:
  - brew update
  - /usr/bin/which ruby
  - ruby --version

install:
  - brew tap csdms/models
  - brew tap --repair
  - brew install hydrotrend sedflux
  - brew test hydrotrend sedflux
