language: objective-c

before_install:
  - brew update
  - /usr/bin/which ruby
  - ruby --version

install:
  - brew tap csdms/models
  - brew tap --repair
  - brew install hydrotrend
  - brew test hydrotrend
  - brew install sedflux --HEAD
  - brew test sedflux
